### ISSUE TITLE
How to access local video?

### ISSUE THREAD

**Issue by sonnguyen1996** [eyeson-team/android-sdk#2]
Hello dev team,

I'm very interested in your work, I tent to use eyes on SDK for my demo app in the thesis. I had to get a local video of a user in meeting to send to server-side after that analysis and get emotion detection. But as my understanding, Only one thread can access media stream from camera. So my question is: Is there any way to get video data from Eyeson's meeting surface view?

Best regards,

Son Nguyen

**Comment by ArturKnaus** [comment]
Hi,

you can either create your own version of `SurfaceViewRenderer` and get the `VideoFrame` directly, or if you only need a Bitmap of the current video, you could use the frame listener. Unfortunately the build in frame listener only returns the first received frame after the listener was added.

**Comment by sonnguyen1996** [comment]
Hi,
Thanks for your reply, All I need that is video of current user. Is there anyway to access raw data maybe via api or sdk :D

Best regards

**Comment by ArturKnaus** [comment]
Yea, wit a custom version of `SurfaceViewRenderer`. The you can override the `onFrame` callback which will provide you the video frames in I420 format.

**Comment by sonnguyen1996** [comment]
You mean that What I need is implement a  SurfaceViewRenderer base on your work, isn't it?

**Comment by ArturKnaus** [comment]
Exactly, as of yet we do not provide a prebuild way to restream the inbound/outgoing video.

**Comment by sonnguyen1996** [comment]
Many thank for your support!
